import type { Metadata } from "next";
import { Geist, Geist_Mono, Public_Sans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "sonner";
// import { Navbar } from "./(authGroup)/_components/shared/navbar";
// import { getMe } from "./service/getMe";
// import { cookies } from "next/headers";
// import jwt from "jsonwebtoken"

import { cookies } from "next/headers";
import jwt, { JwtPayload } from "jsonwebtoken"
import { Navbar } from "./(authGroup)/_components/shared/navbar";

const publicSans = Public_Sans({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // const cookieStore = await cookies();
  //     const accessToken = cookieStore.get("accessToken")?.value;
  //     console.log("accessToken:",accessToken);

  //     const decoded = jwt.decode(accessToken)

  //     console.log(decoded);

  // const user = await getMe();

  // const user = tokenParser();
  // console.log(user);

  // const cookieStore = await cookies();
  //           const accessToken = cookieStore.get("accessToken")?.value;
  
  
  //           if(!accessToken){
  //             return null;
  //           }
  //         //   console.log("accessToken:",accessToken);
      
  //           const user = jwt.decode(accessToken)

            // console.log(user);

// type NavProps = {
//   id: string,
//   name: string,
//   email: string,
//   role: string,
//   iat:number,
//   exp: number
// }



const cookieParser = async () => {

         const cookieStore = await cookies();
                const accessToken = cookieStore.get("accessToken")?.value;



                
                    if(accessToken){
                      const user = jwt.decode(accessToken);
                    // console.log(user);
                    return user;
                
      
                    }
      
                if(!accessToken){
                    const user =  {
                            id: "id",
                            name: "name",
                            email: "email",
                            role: "role",
                            iat:"number",
                            exp: "number"
                        }
                  return user;
                }
                // console.log("accessToken:",accessToken);
          
                

    }

    const fromCookie  = await cookieParser();

    // console.log(fromCookie);

//     const fromCookie: Promise<
//   (jwt.Jwt & (jwt.JwtPayload | (jwt.JwtPayload & string))) | null
// >

    // const fromCookie: Promise<(jwt.Jwt & (jwt.JwtPayload | (jwt.JwtPayload & string))) | null>





  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", publicSans.variable)}
    >
      <body className="min-h-full flex flex-col">
        <Navbar user={fromCookie} ></Navbar>
        <Toaster position="top-right" />
        {children}</body>
    </html>
  );
}
